baseURL = "https://ziggy6792.github.io/"
languageCode = "en-us"
title = "Simon's blog"
theme = "mainroad"

paginate = "10" # Number of posts per page

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[Params]
  subtitle = "Personal tech blog " # Subtitle of your site. Used in site header
  description = "Technical blog about serverless, AWS, React, ... " # Site description. Used in meta description
  copyright = "Mofos Engineering Ltd" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  #mainSections = ["post", blog", "news"] # specify section pages to show on home page and the "Recent articles" widget
  #dateformat = "2006-01-02" # change the format of dates

[Params.sidebar]
  home = "right"
  list = "left"
  single = false
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # linkedin = "username"
  # email = "vincent.drl@gmail.com"